#!/usr/bin/env bash
# this script that transfers a file from a client to a server.
# and Accepts 4 parameters
if (($# < 3))
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/
fi
