#!/usr/bin/env bash
# this script will try to find a solution about why the web server isn't listening the port 80

rm -rf /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo ufw allow 'Nginx HTTP'
service nginx restart
